# Give the workflow a name. 
name: docker-crystal weekly build image

# Trigger Workflow every midnight UTC

on:
  schedule:
    - cron: '0 0 * * 6'  

  push:
    branches:
      - 20.04-0.36
      - 20.04-1.0

jobs:
  build:
    name: Building
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: nelonoel/branch-name@v1.0.1
      - name: Build Docker image
        run: |
          docker build --tag neuralegion/crystal:$BRANCH_NAME \
            --tag neuralegion/crystal:1.0 \
            --tag neuralegion/crystal:latest .
      - name: Login into Docker
        run: docker login --username=anatol1988 --password=${{ secrets.DOCKER_TOKEN }}
      - name: Push Docker image
        run: docker image push --all-tags neuralegion/crystal
